spring.application.name=hogwarts
spring.datasource.url=jdbc:postgresql://ad-postgres2.ctavhiaakoai.us-east-1.rds.amazonaws.com/hogwarts
spring.datasource.username=postgres
spring.datasource.password=12345678
springdoc.swagger-ui.path=/documentacion
springdoc.swagger-ui.operationsSorter=method 
spring.jpa.show-sql=true